### ISSUE TITLE
Issue Report: Complex.js v2.0.0 Causing Uncaught TypeError and Breaking Projects

### ISSUE THREAD

**Issue by omiramontest** [rawify/Complex.js#47]
### **Description**:

Upon upgrading to `complex.js` version 2.0.0, projects that rely on this library are encountering the following error:

```javascript
Uncaught TypeError: Cannot set properties of undefined (setting 'constructor')
```

This error occurs when trying to use core functionalities of the library, specifically when invoking certain classes or functions within the `Complex.js` file. This issue is severely impacting projects, preventing them from running successfully after the update.

---

### **Steps to Reproduce**:

1. Install `complex.js` version 2.0.0 in a project.
2. Attempt to use any method from the `Complex.js` class.
3. The following error appears in the console:
    
``` javascript
    Uncaught TypeError: Cannot set properties of undefined (setting 'constructor')
    at push.../node_modules/mathsjs/lib/esm/type/complex/Complex.js.Object.isClass (Complex.js:14:10)
```
    
    This can be seen in the stack trace provided in the attached screenshot.
    

---

### **Expected Behavior**:

The `complex.js` library should work as expected without throwing any runtime errors. Methods such as `Complex.isClass()` and other core functionalities should be stable and should not result in undefined properties.

---

### **Actual Behavior**:

- The application crashes with the error `Uncaught TypeError: Cannot set properties of undefined (setting 'constructor')`.
- This breaks the functionality of projects depending on `complex.js`.

---

### **Error Stack Trace**:

```bash
Uncaught TypeError: Cannot set properties of undefined (setting 'constructor')
    at push.../node_modules/mathsjs/lib/esm/type/complex/Complex.js.Object.isClass (Complex.js:14:10)
    at assertAndCreate (factory.js:35:1)
    at .../pureFunctionsAny.generated.js:12:55
    at .../mainAny.js:1:1

```

See the attached image for the full error trace.

### **Impact**:

This issue breaks projects that rely on `complex.js` for complex number calculations or other mathematical operations, causing downtime and failures in production environments.

---

### **Possible Solution**:

A temporary solution is to downgrade the library to a stable version. Installing `complex.js` version 2.1.1 has been confirmed to resolve the issue. Please investigate the breaking changes introduced in version 2.0.0 and either patch the release or provide clear documentation for migration.

```bash
npm install complex.js@2.1.1
```
---

### **Additional Context**:

- In our case, the issue surfaced because the ***mathjs*** library uses complex.js as a dependency, which caused our entire project to break upon upgrading.

**Comment by infusion** [comment]
Thanks for reporting this issue! I upgraded some libraries yesterday and also tested it with @josdejong (from mathjs) so that everything works, but I'll look into it again

**Comment by infusion** [comment]
Tried to reproduce it in mathjs:

```
import {complex} from 'mathjs'

console.log(complex(123))
```

Output: `Complex { re: 123, im: 0 }`

This works. Installing complex.js as you mentioned directly in a new project and:

```
let Complex = require('complex.js');

console.log(Complex(123));
```

Works as well. Trying it with "type":"module" in package.json:

```
import Complex from 'complex.js';

console.log(Complex(123));
```

Works also as expected with output `Complex { re: 123, im: 0 }`. Could you please delete the node_modules and package-lock.json? Maybe some caching errors here?

**Comment by infusion** [comment]
Okay, I run a few more scenarios with my friend @freddie-freeloader and were able to spot your problem. Hopefully 2.2.1 fixes your problem!

**Comment by infusion** [comment]
If the problem persists, please reopen this issue
