### ISSUE TITLE
Complex.js Version 2.2.1 problem 

### ISSUE THREAD

**Issue by 3pos** [rawify/Complex.js#48]
We have the following problem since today:
Uncaught TypeError: Cannot set properties of undefined (setting 'type')
in Complex.js Line 11
 -> Complex.prototype.type = 'Complex';

It seems this library is used together with math.js which we're using.
Basically the whole VueJS2 App isn't usable anymore after the update. Build is succeeding but as soon you open it you get that nasty error.
Can you fix/revert that please?

**Comment by 3pos** [comment]
We now pinpointed the version to "complex.js": "2.1.1" which seems to work for now.

**Comment by infusion** [comment]
That's nasty, thanks for your bug report! We worked on improving the build process of the libs and tested it with math.js as well. I'll set up a vuejs app with mathjs to reproduce your issue here.

**Comment by infusion** [comment]
Okay, after striving through vue.js artefacts to figure out what's going wrong, I finally found the problem and pushed v2.2.2. Please remove your version pinning and thanks again for bringing this up so quickly!
If you still have problems, please reopen this issue.

**Comment by trueaniki** [comment]
@infusion it seems like the issue persists in 2.2.3: https://github.com/josdejong/mathjs/issues/3277#:~:text=After%20moving%20to%20version%3A%202.2.3%2C%20the%20problem%20persists.
I personally can confirm that. Could you reopen the issue?

**Comment by infusion** [comment]
Could you also please give some hints about what environment you're using?

**Comment by josdejong** [comment]
@trueaniki what kind of setup do you use? Vite, Webpack, or something else? CommonJS or ESM? Etc.

**Comment by JunaidMazharMuhammad** [comment]
It is not working even tried manually adding old verison 2.1.1

**Comment by infusion** [comment]
If nothing helps, please zip a small version of your problem to reproduce it here and send it to my email address you can find in the complex.js package.json.

**Comment by rebitco** [comment]
I had the same problem.
node: v14.21.2
complex.js: v2.2.3
mathjs: 9.5.2

The mathjs install in my component library, How can I locked the version number of complex2.1.1?

**Comment by infusion** [comment]
@rebitco for you the same offer, could you bundle me a small demo to reproduce it here? I can install node 14 with NVM, but even with this version everything works that I tested. Please send me a small version to reproduce this problem here on my machine using the email address in the package.json.

**Comment by lakatosandrei** [comment]
Hey @infusion 
Just tested building the `complex.js` package with your new `crude-build` (0.0.6) and it seems like it fixes the problem for my case. (A similar issue as the above, using the mathjs package as a dependency, which has `"complex.js": "^2.0.15"`)

Could you please release the new version asap?

Thanks for getting to the bottom of this!

**Comment by lakatosandrei** [comment]
Latest one works for me @infusion .
Thanks for the quick fix!

**Comment by rebitco** [comment]
Everything is running normally now, thank you very much for your timely repair。 @infusion
