### ISSUE TITLE
`new Complex(-0, -0)` is changed into `new Complex(0, 0)` since v2.4.1

### ISSUE THREAD

**Issue by josdejong** [rawify/Complex.js#50]
In commit https://github.com/rawify/Complex.js/commit/6ee03df1bef664715f2efa5c85e6d387ec2d8e4e the use of `parseFloat` is introduced. It turns out that `parseFloat(-0)` returns `0` and not `-0`.

I came across this when unit testing the result of `new Complex(1).acosh()`, which returns `{ re: -0, im: 0 }`, but it is now impossible to create a complex value that holds a `re` value of `-0`, which needed to compare that outcome in a unit test 😅.

**Comment by infusion** [comment]
Interesting, `parseFloat(-0)==0`. Should I revert the use of parseFloat?

**Comment by josdejong** [comment]
What was the reason for adding `parseFloat`? Is it to parse string input?

**Comment by infusion** [comment]
I used Complex.js somewhere and and just split() a string and passed the array as argument to Complex.js, while I wondered that this way the return value contained string and saw that for arrays and objects this wasn't the way it was implemented.

**Comment by josdejong** [comment]
To solve this I think it would be good to create your own `parseInputValue` helper function, which first checks whether the input is a string and only then parse it. You could consider using `Number` instead of `parseFloat` (see https://stackoverflow.com/a/11988751/1262753).

**Comment by donhatch** [comment]
@josdejong wrote:
> To solve this I think it would be good to create your own `parseInputValue` helper function, which first checks whether the input is a string and only then parse it. You could consider using `Number` instead of `parseFloat` (see https://stackoverflow.com/a/11988751/1262753).

But beware that `Number()` has its own problems, as someone pointed out in a comment in one of the answers to that stackoverflow question.

I've used this:

```
      // Do not use parseFloat for this, since that ignores trailing stuff.
      // However, beware that the Number constructor unhelpfully converts
      // zero-or-more spaces to 0.
      let value = /^\s*$/.test(valueString) ? NaN : Number(valueString);
```

**Comment by infusion** [comment]
Alternatively, the easier route would be to revert the change and add a note in the readme that the elements of objects and arrays should be Number.

**Comment by josdejong** [comment]
Yes indeed😄

**Comment by infusion** [comment]
Done, sorry for the interlude.

**Comment by josdejong** [comment]
Thanks, all looks good again 👍
